package com.zZooper.mapper;

import com.zZooper.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    int insertSelective(User record);

    /**
     * 通过用户名查询用户
     * @param userName
     * @return
     */
    public User queryByUserName(String userName);
}