package com.zZooper.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USERNAME
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USERNAME
     *
     * @return the value of T_USER.USERNAME
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.USERNAME
     *
     * @param username the value for T_USER.USERNAME
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PASSWORD
     *
     * @return the value of T_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PASSWORD
     *
     * @param password the value for T_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 17 14:05:29 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}